### ISSUE TITLE
Move TAL specification from Zope2Book to here, likewise for TALES, ZPT?

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.tal#9]
It currently lives at https://github.com/zopefoundation/zope2docs/blob/master/docs/zope2book/AppendixC.rst and on the web at https://docs.zope.org/zope2/zope2book/AppendixC.html.

It seems to me that it would make more sense if it lived here and was published at zopetal.readthedocs.io, as the "Zope 2" book gives the wrong idea about what it is and who uses it.

I'd like to extract the TAL and  METAL parts of the spec from AppendixC and bring them to a document here, and then update AppendixC to refer to the new locations.  I'd like to do the same for the TALES and Page Template sections of that document for zope.tales and zope.pagetemplate. The TALES document in particular is missing documentation for some expression types (lazy and defer) and could use some updating.

Possible concern: zopefoundation/Zope appears to use both zope.pagetemplate/zope.tales and z3c.pt for its implementation of page templates (it's not clear to me exactly what gets used for what), so by bringing the documentation closer to this implementation we might deviate from what is actually available in Zope2. To an extent this has already happened, as `first` and `last` are not available in zope.tal/zope.tales [or Chameleon](https://github.com/malthe/chameleon/issues/249)---to the extent that I know about implementation differences, I can call them out in the documentation.

Thoughts?

**Comment by freddrake** [comment]
The specifications used to live at wiki.zope.org, but that's gone now.

We were very careful to separate the specifications from the implementations, and there are other implementations (though I'm not aware of their current status).

I'd rather see a separate repository for the specifications, though all three (TAL, TALES, METAL) could reasonably all be managed in a single repository.

(I might have an export from wiki.zope.org somewhere, but it may require some digging into dead computers to locate.)

**Comment by jamadden** [comment]
There's an export from the wiki at https://github.com/zopefoundation/zpt-docs, but all the docs are in .stx format so it would take some work to republish them.

Chameleon is an implementation of TAL + page templates + python expressions; z3c.pt adds path expressions. It has some extensions (e.g., it can unpack sequences in `tal:define` and it has `tal:switch`/`tal:case`). It has its own [reference documentation](https://chameleon.readthedocs.io/en/latest/reference.html) that appeared to be copied from AppendixC to start with, but it has diverged (I've recently made some updates to it).

The Zope2 implementation has some differences as well, like the `first`/`last` thing I mentioned above.

There's something called [SimpleTAL](http://owlfish.com/software/simpleTAL/) (plasTeX used to use it), but it doesn't seem to be actively maintained.

This isn't super-important to me because I know where the sources for AppendixC.rst are. I just didn't like having to link to docs.zope.org for all the "narrative" documentation about zope.tal and zope.tales---partly because of the impression that "Zope 2" gives,  partly because that documentation is not maintained anymore (zope.readthedocs.io has the new Zope book, but it doesn't have AppendixC anymore), and partly because docs.zope.org has gone down before.

If a preferred option is to have something like 'zpt.readthedocs.io' to host the contents of AppendixC.rst, and maybe eventually resurrect some of those wiki docs, I would be fine with that.

**Comment by jamadden** [comment]
I've started on this at https://zpt.readthedocs.io

The repo is currently in my own personal github, but if this seems valuable enough to keep going, I'll happily transfer the repo to zopefoundation.

**Comment by jamadden** [comment]
I've ported all the old documentation [from the wiki](https://github.com/zopefoundation/zpt-docs) to ReST and added it to http://zpt.readthedocs.io/en/latest/#historical-documents

**Comment by icemac** [comment]
@jamadden Very nice work! Thank you for your hard work bringing these documents together resp. converting them. I like it very much. I think it is a good idea to keep the specification separate from the implementations. Maybe https://pagetemplates.readthedocs.io could be a nicer subdomain name at RTD.

Are you planning to contribute the repository to zopefoundation?

**Comment by jamadden** [comment]
> Maybe https://pagetemplates.readthedocs.io could be a nicer subdomain name at RTD.

I like it. I've snagged it.

> Are you planning to contribute the repository to zopefoundation?

I would be very happy to, given that there seems to be some interest. How should that proceed?

**Comment by mgedmin** [comment]
> How should that proceed?

(GitHub repository) Settings -> Options -> Danger Zone -> Transfer Ownership

"Transfer this repository to another user or to an organization where you have the ability to create repositories."

**Comment by jamadden** [comment]
Thanks!

I actually meant more from an administration/copyright/legal standpoint; is there any paperwork or whatnot? The docs were all originally from a zopefoundation repository, but I've put enough work into them that they *probably* count as a substantially different albeit derivative work (IANAL). Is me saying "I hereby transfer all claims to Zope Foundation" enough? I do hereby transfer all clams to Zope Foundation, BTW.

**Comment by mgedmin** [comment]
IANAL, but the Committer Agreement says that "by committing a change or new work to the Zope source Repository, you agree to assign and hereby do assign a one-half interest of <...> copyright".  So pushing to a zopefoundation owned repo should be sufficient, as long as you have the right to do the copyright assignment, which seems to be the case for all the new bits that didn't originally come from a ZF owned repo.

**Comment by jamadden** [comment]
Cool!

So I tried the transfer, and it fails because zopefoundation/zpt-docs already exists.

Do we want to rename the existing repository (zpt-legacy-docs)? Or do we want to rename the incoming repository (suggestions welcome)?

**Comment by freddrake** [comment]
@jamadden: Was your repo created from a clone of zopefoundation/zpt-docs, or was it created from scratch?

**Comment by jamadden** [comment]
@freddrake From scratch. There was no actual history in zopefoundation/zpt-docs to preserve so it was easier that way.

**Comment by freddrake** [comment]
OK, makes sense.

I'd be fine with renaming **zopefoundation/zpt-docs** to **zopefoundation/zpt-legacy-docs** if that makes progress easier.

**Comment by jamadden** [comment]
https://github.com/zopefoundation/zpt-docs  is now the converted, Sphinx-ified copy, and https://pagetemplates.readthedocs.io builds from there.

**Comment by icemac** [comment]
@jamadden Thank you! Can we close this issue now or are there still things which should be done?

**Comment by jamadden** [comment]
@icemac Can we use this as a meta tracker for the ZTK places that need updated to refer to the new docs? What I'm aware of:

- [ ] zope.tal (#10)
- [ ] zope.tales
- [ ] zope.pagetemplates

**Comment by jamadden** [comment]
All the outstanding links I could find in ZTK have been changed, so I'll close this. Thanks everyone!

**Comment by icemac** [comment]
Thank you very much! 🥇
